### ISSUE TITLE
The report fails to generated if "SqlValueExpression " is passed

### ISSUE THREAD

**Issue by malhayek2014** [mkurayan/EFDynamicReport#2]
I see an issue where setting the column that I want returned

```
        using(BaseContext context = new BaseContext() )
        {
            CustomerMapper Template = new CustomerMapper(context);

            IReportModel ReportModel = Template.CreateReport();

            var filters = new IReportFilter[0];

            var columns = new IReportColumn[]
            {
                new ReportColumn { Title = "First Name", SqlValueExpression = "(Customer_c.FirstName)"}
            };
            var records = ReportModel.Get(columns, filters);

            return View(records);
        }
```

Please note that without adding `SqlValueExpression = "(Customer_c.FirstName)"` I get an exception `Unknown report column: First Name`

I am also carious why would you implemented an alias. why not just use the actual table name as alias?

Also, how can I use `OutputValueTransformation` and `InputValueTransformation` to transform the data? would you mind providing me a quick example?

Finally, Is there a way to handle joins? so If we need to join 2 different models, is that possible?

**Comment by malhayek2014** [comment]
@mkurayan I update the issue. Thank you for your help

**Comment by mkurayan** [comment]
HI @malhayek2014 Thanks for your questions.

You need to specify 'SqlValueExpression' for report column, you can make custom expression or use C# lambda: 
`studentTable.Column("First Name", x => x.FirstName).`

See demo for more details. [Mapping](https://github.com/mkurayan/EFDynamicReport/blob/master/DynamicReport.Demo/Models/SchoolReportsMapping/StudentsReport.cs)

I used alias instead of real table names in case if you need to write complicated SQL query. 
This is a rare case but if you for example want to join SQL table to itself aliases could be useful.

You can use `OutputValueTransformation`and `InputValueTransformation`when you need process data in C#.
See [Age](https://github.com/mkurayan/EFDynamicReport/blob/master/DynamicReport.Demo/Models/SchoolReportsMapping/Columns/Age.cs) in Demo project for more details. 

You can use the same columns definition in different reports, for example in my Demo project I can create another report, and use (Age, and Score columns in it).

//New Report definition
`
                    {

```
                    _studentTable.Column("First Name", x => x.FirstName),

                    new AverageScore(...).Column("Average Score"),

                    new Age(...).Column("Age"),

                    new Subjects(...).Column("Subjects")
                }
```

`

**Comment by malhayek2014** [comment]
@mkurayan.  Thank for your help with this. You mention joins, how can you handle joins this this case? Can I define relations in my mapper class?

**Comment by mkurayan** [comment]
@malhayek2014 Sorry i did not implement relation mapping, but if you want to use many tables as source you can JOIN them in code.
![joxi](https://cloud.githubusercontent.com/assets/9530261/16546418/49f45442-4152-11e6-9e97-08c541d8581f.jpg)

Or in order to get School Name you can create new custom column SchoolName (the same way how we created Age, Subjects and other custom columns, See Demo project)
